config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "movies#index"
  
  # verb "url" => "name_of_controllers#name_of_action"
  get "movies" => "movies#index"
  
  # Variables in routes start with a colon (:)
  # All URL request parameters are automatically captured by Rails in a Ruby hash called params. 
  # You can access this hash inside of any controller action. 
  # In this case, because the route has a variable named :id, you can get the movie id that's embedded in the URL by accessing params[:id].
  get "movies/:id" => "movies#show", as: "movie"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    def flop?
       total_gross.blank? || total_gross < 50000000 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all 
	end
	
	def show
		@movie = Movie.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def format_total_gross(movie)
        if movie.flop?
            # HTML strings returned from helper methods will automatically be escaped by default to prevent cross-site scripting. 
            # Strings returned from helpers that should not be escaped (e.g. strings containing HTML tags) must be marked as HTML-safe 
            # by calling the html_safe method on the string. 
            # Alternatively, you can use the content_tag helper which always returns an HTML-safe string with the content surrounded by the tag.
           content_tag(:strong, 'Flop!' )
           # this also work: "<strong>Flop!</strong>".html_safe
        else
            number_to_currency(movie.total_gross)
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1><%= pluralize(@movies.size, 'Movie') %></h1>

<% @movies.each do |movie| %>
	<article>
	    <!--<header><h2><%= link_to(movie.title, movie_path(movie.id)) %></h2></header>-->
	    <!--When generating links to an object's show page, you can pass that object as the second parameter to link_to-->
	    <!--you don't have to call the named route method. Given the movie object, the link_to method assumes that it should call the movie_path method for you-->
	    <header><h2><%= link_to movie.title, movie %></h2></header>
	    <!--the separator key make sure the shortened description breaks on a space rather than chopping off a word-->
	    <p><%= truncate(movie.description, length: 40, separator: ' ') %></p>
	    <table>
	        <tr>
	            <th>Release:</th>
	            <td><%= movie.released_on.to_s(:release_date) %> (<%= time_ago_in_words(movie.released_on) %> ago)</td>
	        </tr>
	        <tr>
	            <th>Rating:</th>
	            <td><%= movie.rating %></td>
	        </tr>
	        <tr>
	            <th>Total Gross:</th>
	            <td><%= format_total_gross(movie) %></td>
	        </tr>
	    </table>
	</article>
<% end %>


app/views/movies/show.html.erb
<article>
    <header>
        <h1><%= @movie.title %></h1>
    </header>
    <h2>Description</h2>
    <p><%= @movie.description %></p>
    <h3>Rating</h3>
    <p><%= @movie.rating %></p>
    <h3>Release On</h3>
    <p><%= @movie.released_on %> (<%= time_ago_in_words(@movie.released_on) %> ago)</p>
    <h3>Total Gross</h3>
    <p><%= format_total_gross(@movie) %></p>
</article>

<%= link_to("All Movies", root_path) %>